Check spots available
Amotul-raheem/park-booking-service pull request #2
Opened 2022-04-02 19:37 UTC by Amotul-raheem

this endpoint checks the data base to see pending bookings. it compares the check in and check out dates to those in the database to see if doesn't fall in the range of any pending bookings. And it returns list of unavailable parking spots.

2022-04-02 19:39 UTC, Amotul-raheem commented on routes/SpotsAvailable.js
> +                unavailableSpots.push(x)
I'm having issue with this if statement. Everything under it is nit implementing and i think has somethin to do with the date format. Still trying to resolve it.

2022-04-02 19:40 UTC, Amotul-raheem commented on routes/SpotsAvailable.js
> +// Usage
i haven't cleaned up the code yet. Will get rid of these soon.

2022-04-02 19:41 UTC, Amotul-raheem commented on routes/BookingRouter.js
> -bookingRouter.post("/isSpotAvailable", async (req, res) => {
This was my previous approach. couldn't get it to work

2022-04-03 21:47 UTC, folaraz requested changes

2022-04-03 21:47 UTC, folaraz commented on app.js
> +app.use("/api", spotsAvailableRouter);
change name to ParkSpotRetreiver

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsAvailable.js
> +        let x = (pendingBookings[i].space_id);
🙄 whats x?

2022-04-03 21:47 UTC, folaraz commented on app.js
> +app.use("/api", totalSpotsRouter);
change it to ParkSpotsRouter, that name doesn't make sense

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +const totalSpotsRouter = express.Router();
Change to ParkSpotRouter, don't forget

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +        let totalSpots = {}
call it allParkSpots instead

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +        let availableSpots = fulfilledAndCancelledBookings.map(getAvailableSpaceId)
it's returning spotIds not spots. So say availabeSpotIds.


you don't need a new getAvailableSpaceIds function. You can easily, do `let availableSpotIds = fulfilledAndCancelledBookings.map(booking => booking.space_id);`

Therefore, you don't  need the function you wrote below. Also, the function doesn't look right to me.

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +        let unavailableSpots = pendingAndInuseBookings.map(getUnavailableSpaceId)
same here, unavailabeSpotIds

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +        function getUnavailableSpaceId(booking) {
This won't work. You pushing  to an array while looping through the pendingAndInUseBookings, doesn't make sense.


Use the example below to fix it and make a callback for line 20
`const euro = [29.76, 41.85, 46.5];

const above30 = euro.reduce((total, amount) => {
  if (amount > 30) {
    total.push(amount);
  }
  return total;
}, []);

above30 // [ 41.85, 46.5 ]`

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +        res.status(200).send("Parkspaces updated successfully")
are we not meant to return all the spots?

2022-04-03 21:47 UTC, folaraz commented on routes/SpotsRouter.js
> +totalSpotsRouter.post("/isSpotAvailable", async (req, res) => {
this endpoint should not be called isSpotAvailable, instead getParkSpots

2022-04-03 21:47 UTC, folaraz commented on utils/BookingStatus.js
> +    INUSE: "IN-USE"
change from IN-USE to IN_USE

2022-04-03 23:39 UTC, folaraz approved these changes

2022-04-04 20:58 UTC, folaraz approved these changes

2022-04-04 21:00 UTC, folaraz approved these changes

2022-04-04 21:00 UTC, merged